spring:
  profiles:
    active: local
  application:
    name: leikooo-code-mother
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leikooo_code_mother
    username: root
    password: <password>
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60
      database: 10
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  mail:
    host: smtp.126.com
    port: 465
    username: xxxxxxx@126.com
    password: 授权密码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            fallback: false
    protocol: smtp
  ai:
    openai:
      api-key: <API-KEY>
      base-url: https://api.qnaigc.com
      chat:
        options:
          model: minimax/minimax-m2.1
          temperature: 0.2
          stream-usage: true
          logprobs: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            platform: mysql
server:
  port: 8438
  servlet:
    context-path: /api
sa-token:
  jwt-secret-key: key

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      packages-to-scan: com.leikooo.codemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn